# Task 5 configuration

# Lightweight vision model for visual classification
CLASSIFICATION_MODEL = "MobileNet_V3_Small"

# Image captioning model
CAPTION_MODEL = "Salesforce/blip-image-captioning-base"

# Maximum image size used during processing
MAX_IMAGE_SIZE = (384, 384)

# Maximum number of tokens generated by the captioning model
MAX_NEW_TOKENS = 15

# Minimum confidence required before treating an image
# classification as strong visual evidence
CLASSIFICATION_CONFIDENCE_THRESHOLD = 0.50

# Number of previous conversation turns to retain
MAX_HISTORY_TURNS = 6

# Minimum evidence score required for a validated answer
EVIDENCE_THRESHOLD = 0.50